---
version: 2

updates:
  - package-ecosystem: "npm"
    assignees:
      - "JanaME"
    commit-message:
      prefix: "deps"
      include: "scope"
    cooldown:
      default-days: 7
    directory: "/src/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Berlin"

  - package-ecosystem: "github-actions"
    assignees:
      - "JanaME"
    cooldown:
      default-days: 7
    directory: "/.github/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Berlin"